### ISSUE TITLE
Without graph in x11docker

### ISSUE THREAD

**Issue by heylypp** [lajoiepy/argos3_docker_example#1]
I just follow the guide, but it can't work properly. I wonder where the problem is.
The environment: ubuntu 18.04  I7-6700 16G GeForce GTX 965M
![image](https://user-images.githubusercontent.com/16957782/104815543-24070580-5850-11eb-9a26-d6c18db52b5a.png)

**Comment by lajoiepy** [comment]
Hi!
Try the following options: ` --hostdisplay --hostnet --user=RETAIN -- --privileged`.
If this doesn't work, this more an issue for https://github.com/mviereck/x11docker.
Otherwise, there are other solutions out there to share the X server: look into http://wiki.ros.org/docker/Tutorials/GUI or https://github.com/osrf/rocker .
